version: '3.4'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testtest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:51005
    links:
      - mongodb  
    # depends_on:
      #  mysqldb:
      #     condition: service_started
      #  mongodb:
      #     condition: service_started

    tty: true
    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/domain.crt:/etc/nginx/conf.d/domain.crt
      - ./nginx/domain.key:/etc/nginx/conf.d/domain.key
    ports:  
      - 80:80
      - 443:443
    depends_on:
      - backend  

  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    # healthcheck:
    #         test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #         timeout: 20s
    #         retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=testtest
      - MYSQL_DATABASE=backend_test
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql          

volumes:
  mongodb_data_container:    
  db:  